COMMENT =	colourful, human-friendly hexdump tool

DIST_TUPLE +=	github FireyFly hexd v1.1.0 .

CATEGORIES =	sysutils

MAINTAINER =		Yozo TODA <yozo@v007.vaio.ne.jp>

# MIT
PERMIT_PACKAGE =	Yes

# If pledge is used, annotate with `uses pledge()' in a comment

WANTLIB +=		c

FAKE_FLAGS =		DESTDIR=

NO_TEST =		Yes

.include <bsd.port.mk>
