# $OpenBSD: Makefile.template,v 1.88 2020/05/15 01:32:48 abieber Exp $

COMMENT =	get, unpack, build and install modules from CPAN

DISTNAME =	App-cpanminus-1.7044

CATEGORIES =	devel

HOMEPAGE =	https://github.com/miyagawa/cpanminus

MAINTAINER =		Yozo TODA <yozo@v007.vaio.ne.jp>

# perl_5
PERMIT_PACKAGE =	Yes

MODULES =	cpan
PKG_ARCH =	*

.include <bsd.port.mk>
