COMMENT =	meta package for android related tools

PKGNAME =	android-tools-1.0

MAINTAINER =		Yozo TODA <yozo@v007.vaio.ne.jp>

## from meta/Makefile.inc
CATEGORIES=		meta
DISTFILES=		#empty
NO_BUILD=		Yes
NO_TEST=		Yes
PKG_ARCH=		*
PERMIT_PACKAGE=	Yes
do-install:

RUN_DEPENDS =	devel/apktool \
		devel/dex2jar \
		devel/jadx \
		devel/jd-gui

.include <bsd.port.mk>
