COMMENT =	redesigned mplus fonts

MODFONT_FAMILY =	mplus-new-fonts
MODFONT_VERSION =	20260809

COMMIT =	42f53f11e87c18fd687dc50994c396d483ea890d
DIST_TUPLE +=	github coz-m MPLUS_FONTS ${COMMIT} .

HOMEPAGE =	https://mplusfonts.github.io/

MAINTAINER =		Yozo TODA <yozo@v007.vaio.ne.jp>

# SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
PERMIT_PACKAGE =	Yes

MODULES =		font

NO_BUILD =		Yes
NO_TEST =		Yes

MODFONT_FONTFILES =	fonts/*/variable/*.ttf

.include <bsd.port.mk>
