COMMENT =	Japanese Ming-style font

MODFONT_FAMILY =	hanazono
MODFONT_VERSION =	20170904
REVISION =		0

DISTNAME =	hanazono-${MODFONT_VERSION}

CATEGORIES =	fonts japanese

HOMEPAGE =	https://glyphwiki.org/hanazono/

# "Unlimited permission is granted to use, copy, and distribute it,
#  with or without modification, either commercially and noncommercially."
PERMIT_PACKAGE =	Yes

SITES =			${HOMEPAGE}

MODULES =		font

NO_BUILD =		Yes
NO_TEST =		Yes

WRKDIST =		${WRKDIR}

.include <bsd.port.mk>
