COMMENT =	show pretty mascot on your display

DIST_TUPLE +=	github nyan- xmascot v2.6a.20200830 .

CATEGORIES =	x11

HOMEPAGE =	https://cclub-flying.dsl.gr.jp/products/xmascot/

MAINTAINER =	Yozo TODA <yozo@v007.vaio.ne.jp>

# (no license...)
PERMIT_PACKAGE =	Yes

CONFIGURE_STYLE =	imake

NO_TEST =		Yes

.include <bsd.port.mk>
