COMMENT =	colourful visualization tool for binary files

DIST_TUPLE +=	github FireyFly pixd v1.0.0 .

CATEGORIES =	sysutils

MAINTAINER =		Yozo TODA <yozo@v007.vaio.ne.jp>

# MIT
PERMIT_PACKAGE =	Yes

WANTLIB +=		c

FAKE_FLAGS =		DESTDIR=

NO_TEST =		Yes

.include <bsd.port.mk>
