COMMENT =	mixture of M+ and IPA Gothic fonts, focused on kanji

V.20200307 =	20200307
V.20231123 =	20231123
PKGNAME =	migu-${V.20231123}
MODFONT_FAMILY =	migu

CATEGORIES =	fonts

HOMEPAGE =	https://itouhiro.github.io/mixfont-mplus-ipa/migu/

MAINTAINER =	Anthony J. Bentley <anthony@anjbe.name>

# IPA Font License Agreement v1.0
PERMIT_PACKAGE =	Yes

SITES.20200307 =	https://github.com/itouhiro/mixfont-mplus-ipa/releases/download/v2020.0307/
SITES.20231123 =	https://github.com/itouhiro/mixfont-mplus-ipa/releases/download/v2023.1123/

DISTFILES.20200307 =	migu-1c-${V.20200307}.zip \
			migu-1m-${V.20200307}.zip \
			migu-1p-${V.20200307}.zip
DISTFILES.20231123 =	migu-2m-${V.20231123}.zip

MODULES =	font

NO_BUILD =	Yes
NO_TEST =	Yes

MODFONT_FONTFILES =	*/*.ttf

.include <bsd.port.mk>
